site_name: Physical Atmosphere²
theme:
  name: material
  custom_dir: theme-extension
  favicon: img/physical-addons-favicon.svg
  logo: img/physical-addons-logo-white.svg
  palette:
    primary: black
  features:
    - navigation.top
plugins:
  - search
site_url: https://www.physicaladdons.com/physical-atmosphere/
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.keys
  - attr_list
  - abbr
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      toc_depth: '1-2'
      permalink: true
nav:
  # - Home: index.md
  - Getting Started: getting-started.md
  - Documentation: documentation.md
  - Release notes: release-notes.md
extra_css:
  - stylesheets/extra.css
extra:
  analytics:
    provider: plausible
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/wvzPVzj9Vr
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/PhysicalAddons
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/PhysicalAddons/
    - icon: fontawesome/brands/github
      link: https://github.com/PhysicalAddons/
